server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
management:
  context-path: /management
  security:
    enabled: false